name: Go
on:
  release:
    type:
      - created
jobs:

  build-and-publish:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      run: |
        git clone https://brannondorsey:$GITHUB_TOKEN@github.com/brannondorsey/vanity-keygen
        echo git remote -v
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get dependencies
      working-directory: ./vanity-keygen
      run: |
        make deps

    - name: Build for all platforms
      working-directory: ./vanity-keygen
      run: make build-all

    - name: Snapshot and Release
      working-directory: ./vanity-keygen
      run: make snapshot

    - name: Upload artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'vanity-keygen/bin/*.zip vanity-keygen/bin/*.tar.gz'
